vim.wo.number = true                   -- Make line numbers default (default:false)
vim.o.relativenumber = true            -- Set relative numbered lines (default:false)
vim.o.clipboard = 'unnamedplus'        -- Sync clipboard betwen OS and Neovim. (default: '')
vim.o.linebreak = true                 -- Companion to wrap, don't split words (default:'')
vim.o.mouse = 'a'                      -- Enable mouse mode (default:'')
vim.o.autoindent = true                -- Copy indent from current line when starting new one (default:true)
vim.o.ignorecase = true                -- Case-insensitive searching UNLESS \C or capital in search (default:false)
vim.o.smartcase = true                 -- Smart case (default:false)
vim.o.shiftwidth = 4                   -- the number of spaces inserted for each indentation
vim.o.tabstop = 4                      -- insert n spaces for a tab
vim.o.softtabstop = 4                  -- Number of spaces that a tab counts for while performing editing operations
vim.o.expandtab = true                 -- convert tabs to spaces
vim.opt.termguicolors = true           -- set termguicolors to enable highlight groups
vim.o.breakindent = true               -- Enable break indent
vim.o.completeopt = 'menuone,noselect' -- Set completeopt to have a better completion experience
vim.wo.signcolumn = 'yes'              -- Keep signcolumn on by default
